# Generated by Django 4.0.4 on 2022-05-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='user',
        ),
    ]
