# Generated by Django 4.0.4 on 2022-05-22 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_alter_customuser_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('s_date', models.DateField(max_length=100)),
                ('e_date', models.DateField(default=datetime.date(2022, 5, 23))),
            ],
        ),
    ]
