# Generated by Django 4.0.4 on 2022-05-28 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_alter_career_e_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='certificate',
        ),
    ]
