# Generated by Django 4.0.4 on 2022-05-23 14:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='e_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 23, 14, 45, 54, 853520, tzinfo=utc)),
        ),
    ]
