# Generated by Django 4.0.4 on 2022-05-26 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_alter_career_e_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='e_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
